"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def q2():
	terms = [0,1]
	result = [ ]
	x = 0
	i = 2
	while i<=33:
		terms.append(terms[i-1] + terms[i-2])
		i = i + 1
	print terms

	#result = [ ]
	x = 1
	result = filter(lambda x: x % 2 == 0, terms)
	return sum(result)

"""
	for x in terms:
		if x%2 == 0:
			result.append(x)
	print result
	return sum(result)
"""